<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
$relationships = array (
  'dotb2_application_favorite' => 
  array (
    'id' => '56bf8c4c-4d40-7602-90f1-55db2dc0b2a6',
    'relationship_name' => 'dotb2_application_favorite',
    'lhs_module' => 'dotb2_application',
    'lhs_table' => 'dotb2_application',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Users',
    'rhs_table' => 'users',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'sugarfavorites',
    'join_key_lhs' => 'record_id',
    'join_key_rhs' => 'modified_user_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'dotb2_application',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb2_application_following' => 
  array (
    'id' => '57c86a2e-5c79-1428-864e-55db2d2df5b0',
    'relationship_name' => 'dotb2_application_following',
    'lhs_module' => 'dotb2_application',
    'lhs_table' => 'dotb2_application',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Users',
    'rhs_table' => 'users',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'subscriptions',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'created_by',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'dotb2_application',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb2_application_modified_user' => 
  array (
    'id' => '5880b5c7-7fac-7437-0b94-55db2df6a131',
    'relationship_name' => 'dotb2_application_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb2_application',
    'rhs_table' => 'dotb2_application',
    'rhs_key' => 'modified_user_id',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb2_application_created_by' => 
  array (
    'id' => '59319965-78fe-4e0d-49b2-55db2d89373e',
    'relationship_name' => 'dotb2_application_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb2_application',
    'rhs_table' => 'dotb2_application',
    'rhs_key' => 'created_by',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb2_application_activities' => 
  array (
    'id' => '59e47347-df67-9095-6480-55db2df74a4e',
    'relationship_name' => 'dotb2_application_activities',
    'lhs_module' => 'dotb2_application',
    'lhs_table' => 'dotb2_application',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'rhs_vname' => 'LBL_ACTIVITY_STREAM',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'dotb2_application',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb2_application_assigned_user' => 
  array (
    'id' => '5f4f963a-1b4d-60c8-800e-55db2d6ceded',
    'relationship_name' => 'dotb2_application_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb2_application',
    'rhs_table' => 'dotb2_application',
    'rhs_key' => 'assigned_user_id',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb3_contract_dotb2_application' => 
  array (
    'id' => 'd78b650b-357b-cff9-a8da-55db2d242dfc',
    'relationship_name' => 'dotb3_contract_dotb2_application',
    'lhs_module' => 'dotb2_application',
    'lhs_table' => 'dotb2_application',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb3_contract',
    'rhs_table' => 'dotb3_contract',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'dotb3_contract_dotb2_application_c',
    'join_key_lhs' => 'dotb3_contract_dotb2_applicationdotb2_application_ida',
    'join_key_rhs' => 'dotb3_contract_dotb2_applicationdotb3_contract_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'dotb2_application_dotb1_credit_request' => 
  array (
    'id' => 'da3ad954-de76-33f3-56da-55db2d83acb8',
    'relationship_name' => 'dotb2_application_dotb1_credit_request',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb2_application',
    'rhs_table' => 'dotb2_application',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'dotb2_application_dotb1_credit_request_c',
    'join_key_lhs' => 'dotb2_application_dotb1_credit_requestdotb1_credit_request_ida',
    'join_key_rhs' => 'dotb2_application_dotb1_credit_requestdotb2_application_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
);