<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
$relationships = array (
  'dotb1_credit_request_favorite' => 
  array (
    'id' => '91409ec9-4179-d24c-05cf-564c4f1658a0',
    'relationship_name' => 'dotb1_credit_request_favorite',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Users',
    'rhs_table' => 'users',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'sugarfavorites',
    'join_key_lhs' => 'record_id',
    'join_key_rhs' => 'modified_user_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'dotb1_credit_request',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_following' => 
  array (
    'id' => '91846f61-9932-eb5c-71c9-564c4fa089bf',
    'relationship_name' => 'dotb1_credit_request_following',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Users',
    'rhs_table' => 'users',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'subscriptions',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'created_by',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'dotb1_credit_request',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_modified_user' => 
  array (
    'id' => '91b2a3e3-118e-448b-413f-564c4f516368',
    'relationship_name' => 'dotb1_credit_request_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb1_credit_request',
    'rhs_table' => 'dotb1_credit_request',
    'rhs_key' => 'modified_user_id',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_created_by' => 
  array (
    'id' => '91cef5e9-3faf-6a6f-6b05-564c4f968034',
    'relationship_name' => 'dotb1_credit_request_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb1_credit_request',
    'rhs_table' => 'dotb1_credit_request',
    'rhs_key' => 'created_by',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_activities' => 
  array (
    'id' => '91fa7ded-841a-43a4-2723-564c4f44d9e9',
    'relationship_name' => 'dotb1_credit_request_activities',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'rhs_vname' => 'LBL_ACTIVITY_STREAM',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'dotb1_credit_request',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_assigned_user' => 
  array (
    'id' => '92869eaa-9ab1-6a6e-7cf7-564c4fa45afd',
    'relationship_name' => 'dotb1_credit_request_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb1_credit_request',
    'rhs_table' => 'dotb1_credit_request',
    'rhs_key' => 'assigned_user_id',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_activities_tasks' => 
  array (
    'id' => 'b6fb1f4b-be02-af3e-f628-564c4f16e1d3',
    'relationship_name' => 'dotb1_credit_request_activities_tasks',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'dotb1_credit_request',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_activities_notes' => 
  array (
    'id' => 'b731af72-7d32-2eb9-ddbc-564c4f3085df',
    'relationship_name' => 'dotb1_credit_request_activities_notes',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'dotb1_credit_request',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_contacts' => 
  array (
    'id' => 'b766015e-d9b4-c106-f04e-564c4fcc52e0',
    'relationship_name' => 'dotb1_credit_request_contacts',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb1_credit_request',
    'rhs_table' => 'dotb1_credit_request',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'dotb1_credit_request_contacts_c',
    'join_key_lhs' => 'dotb1_credit_request_contactscontacts_ida',
    'join_key_rhs' => 'dotb1_credit_request_contactsdotb1_credit_request_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForContactsDotb1_credit_request_contacts',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_activities_calls' => 
  array (
    'id' => 'b79e11da-43fd-8146-dcc9-564c4fdce9b8',
    'relationship_name' => 'dotb1_credit_request_activities_calls',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'dotb1_credit_request',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_activities_meetings' => 
  array (
    'id' => 'b7d496a5-fb28-b357-d98c-564c4f55e667',
    'relationship_name' => 'dotb1_credit_request_activities_meetings',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'rhs_vname' => NULL,
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'dotb1_credit_request',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'dotb3_contract_dotb1_credit_request' => 
  array (
    'id' => 'b8a8dba2-acb2-c83a-1666-564c4f1bc053',
    'relationship_name' => 'dotb3_contract_dotb1_credit_request',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb3_contract',
    'rhs_table' => 'dotb3_contract',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'dotb3_contract_dotb1_credit_request_c',
    'join_key_lhs' => 'dotb3_contract_dotb1_credit_requestdotb1_credit_request_ida',
    'join_key_rhs' => 'dotb3_contract_dotb1_credit_requestdotb3_contract_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'dotb2_application_dotb1_credit_request' => 
  array (
    'id' => 'b8e1cc58-d042-8310-eb6d-564c4fbf9b39',
    'relationship_name' => 'dotb2_application_dotb1_credit_request',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'dotb2_application',
    'rhs_table' => 'dotb2_application',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'dotb2_application_dotb1_credit_request_c',
    'join_key_lhs' => 'dotb2_application_dotb1_credit_requestdotb1_credit_request_ida',
    'join_key_rhs' => 'dotb2_application_dotb1_credit_requestdotb2_application_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'dotb1_credit_request_documents_1' => 
  array (
    'id' => 'b95907bb-a4ea-93ea-037f-564c4fd12439',
    'relationship_name' => 'dotb1_credit_request_documents_1',
    'lhs_module' => 'dotb1_credit_request',
    'lhs_table' => 'dotb1_credit_request',
    'lhs_key' => 'id',
    'lhs_vname' => NULL,
    'rhs_module' => 'Documents',
    'rhs_table' => 'documents',
    'rhs_key' => 'id',
    'rhs_vname' => NULL,
    'join_table' => 'dotb1_credit_request_documents_1_c',
    'join_key_lhs' => 'dotb1_credit_request_documents_1dotb1_credit_request_ida',
    'join_key_rhs' => 'dotb1_credit_request_documents_1documents_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'dotb1_credit_request_co_credit_offer_1' => 
  array (
    'rhs_label' => 'Credit Offers',
    'lhs_label' => 'Credit Requests',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'dotb1_credit_request',
    'rhs_module' => 'co_Credit_Offer',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'dotb1_credit_request_co_credit_offer_1',
  ),
);